export default Colors = {
  primary: '',
  secondary: '',
  textPrimary: '',
  textSecondary: '',
  border: '',
  backgroundPrimary: '#8ffbdc',
  backgroundSecondary: '',
  white: '#FFFFFF',
  black: '#000000',
  gray: '#F9F9F9',
  tansparent: 'transparent',
  red: 'red',
  blue: 'blue',
};
